myecommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import home_page, about_page, contact_page,  login_page, logout_page, RegisterView, contact_success, handler404, handler500


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('contactsuccess/', contact_success, name='message_success'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_page, name='logout'),
    path('accounts/', include('allauth.urls')),
    path('shop/', include('shop.urls')),

    # ERRO 404
    # Adicione a seguinte linha para lidar com o erro 404
    re_path(r'^.*/$', handler404),
    re_path(r'^.*/500/$', handler500)
]

shop/urls.py
# store/urls.py
from django.urls import path
from .views import add_to_cart, CartView, ProductListView, OrderListView, Produto_Detail, OrderCreateView, CartItemDeleteView, CategoryListView, CategoryDetailView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, HomeView_management

from myecommerce.views import login_in_detailview, AddressCreateView, AddressDeleteView, AddressUpdateView, UserProfileView


urlpatterns = [
    path('product/<int:pk>/', Produto_Detail.as_view(), name='product'),
    path('login/', login_in_detailview, name='login_view'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/item/<int:pk>/delete/', CartItemDeleteView.as_view(), name='cart-item-delete'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    # Perfil User
    path('user/<int:pk>', UserProfileView.as_view(), name='user-profile'),

    # ADDRESS
    path('address/create', AddressCreateView.as_view(), name='address-create'),
    path('address/<int:pk>/delete/', AddressDeleteView.as_view(), name='address-delete'),
    path('address/<int:pk>/update/', AddressUpdateView.as_view(), name='address-update'),

    path('management', HomeView_management.as_view(), name='home_management'),

    # CATEGORY
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),

    # PRODUCT
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),

]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
        
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name
    

class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    
class Cart(models.Model):
    # Ligaçaõ do usuario associado ao carrinho
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    # Produtos para serem adicionados ao carrinho 
    products = models.ManyToManyField(Product, through="CartItem")

    def __str__(self):
        return f'Cart - {self.user.username}'


class CartItem(models.Model):
    # Nome do produto adicionado ao carrinho
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # Ligação da quantidade de cada item no carrinho
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    # Numero de unidades do pedido
    quantity = models.PositiveBigIntegerField(default=1)

    SIZE_CHOICES = [
        ('Small', 'Small'),
        ('Medium', 'Medium'),
        ('Large', 'Large'),
    ]
    size = models.CharField(
        max_length=10, choices=SIZE_CHOICES, null=True, blank=True)
    # Booleano com padrão False
    is_purchased = models.BooleanField(default=False)
    

    def __str__(self):
        return f'{self.quantity} x {self.product.name} in cart'
    

class Address(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=10)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.street_address

    class Meta:
        verbose_name_plural = 'Addresses'



class Payment(models.Model):
    # Se tiver uma API stripe, (https://stripe.com/br) remova o comentário do campo 'stripe_charge_id' e faça as migrações
    #stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

class OrderItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveBigIntegerField(default=1)
    is_purchased = models.BooleanField(default=False)
    SIZE_CHOICES = [
        ('Small', 'Small'),
        ('Medium', 'Medium'),
        ('Large', 'Large'),
    ]
    size = models.CharField(
        max_length=10, choices=SIZE_CHOICES, null=True, blank=True)

    def __str__(self):
        return f'{self.quantity} x {self.product.name} in order'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(Address, related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'Order - {self.user.username} - {self.order_date}'


# Adiciona itens do carrinho ao pedido após a criação do pedido
@receiver(post_save, sender=Order)
def add_cart_items_to_order(sender, instance, created, **kwargs):
    if created:
        cart_items = CartItem.objects.filter(cart__user=instance.user, is_purchased=False)

        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                product=cart_item.product,
                quantity=cart_item.quantity,
                is_purchased=True
            )
            instance.items.add(order_item)

        # Limpa os itens do carrinho após adicioná-los ao pedido
        cart_items.update(is_purchased=True)
        cart_items.delete()

templates/store/a.html
{% extends 'base.html' %} 
{% load static %}

{% block container %}
<div class="m-auto mt-5 mb-2 p-4">
    <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-12 mt-4 mb-4">
               
        </div>
    </div>

{% endblock container %}

templates/store/cart.html
{% extends 'base.html' %} {% load static %}

{% block container %}
<div class="cart-container w-75 m-auto p-2  bg-light row-cols-2" style="margin-top: 10rem!important;">
   
    
    <div class='row w-100 border-bottom bg-primary-subtle mt-0 mx-1 shadow shadow-sm'>
        <h2 class="col-5">Items in Cart</h2>
        <a href="{% url 'home' %}" class='col-3 btn btn-sm btn-secondary w-25 m-auto d-block'><i class="fa-solid fa-chevron-right fa-rotate-180"></i><i class="fa-solid fa-chevron-right fa-rotate-180"></i> Back to home </a>
        <a href="{% url 'order_create' %}" class='col-3 btn btn-sm btn-primary w-25 m-auto d-block'>To Buy <i class="fa-solid fa-cart-shopping"></i></a>
    </div>
        {% if cart_items %}
            <ul class="row w-100">
                {% for item in cart_items %}
                    <li class='col-5 row m-2 border rounded-2 shadow shadow-sm  '>
                        <div class="col-4 " style="background-color: rgba(255, 255, 255, 0.8)">
                            <img src="{{item.product.image.url}}" class="card-img-top p-4 w-100 h-auto col" alt="pizza">
                        </div>
                        <div class='col-6'>
                            <div class="card-body text-center pt-2">
                                <h6 class="card-title">{{item.product.name}}</h6>
                                {{ item.quantity }} units of {{ item.product.name }} - ${{ item.product.price|floatformat:2 }} per unit
                                <p class='mt-1 mb-1 fs-6'><b>{{item.product.category.name}}'s size:</b>{{ item.size }}</p>
                            </div>
                            <a href="{% url 'cart-item-delete' item.pk %}" class="btn btn-sm btn-danger">"Delete item from the cart."</a>
                            
                        </div> 
                    </li>
                {% endfor %}
            </ul>
        {% else %}
        <p class="text-center">Your cart is empty. <a href="{% url 'home' %}">Browse our products</a>.</p>
        {% endif %}

</div>

{% endblock container %}

templates/store/cart_item_confirm_delete.html
{% extends 'base.html' %} {% load static %}

{% block container %}
<div class="cart-container w-75 m-auto p-2  bg-light row-cols-2" style="margin-top: 10rem!important;">
    <div class='w-100 border-bottom bg-primary-subtle mt-0 mx-1 shadow shadow-sm'>
        <h2 class="fs-3">Delete {{object}} from the cart</h2>
    </div>
    <div class="w-100">
        <form action="" method="post" class="form-control text-center w-100 bg-danger-subtle">
            {% csrf_token %}
            <h3 class="h2 fs-4 ">Are you sure you want to remove this item from the cart?</h3>
            <button type="submit" class="btn btn-sm btn-danger">Delete {{object}} <i class="fa-solid fa-trash"></i></button>
        </form>
    </div>
    
</div>

{% endblock container %}

templates/store/detail.html
{% extends 'base.html' %} {% load static %}

{% block container %}
<style>
    /* Modal Styles */
.modal {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
}

.modal-content {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: white;
  padding: 20px;
  text-align: center;
}

.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
  cursor: pointer;
}

</style>
<div class="m-auto mt-5 mb-2 p-4">
    <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-12 mt-4 mb-4">
                <div class="card" style="width: 16rem;background-color: rgba(255, 255, 255, 0.8)">
                    <img src="{{product.image.url}}" class="card-img-top w-100 p-3" alt="pizza">
                    <div class="card-body text-center">
                        <h6 class="card-title">{{product.name}}</h6>
                        <p class="card-text small">{{product.description}}</p>
                        <p class="card-text">{{product.price}}</p>
                        {% if request.user.is_authenticated %}
                        <hr>
                          <form action="{% url 'add_to_cart' product.id %}" method="get" >
                            {% csrf_token %}
                            <div class="m-2 text-center">
                              <label for="size" class="d-block">Select {{product.category.name}}'s size</label>
                              <select name="size" id="id_size" class="d-block m-auto mb-2 ">
                                <option value="Small">Small</option>
                                <option value="Medium">Medium</option>
                                <option value="Large">Large</option>
                              </select>
                              <button type="submit" class="btn btn-primary btn-sm">Add to Cart</button>
                            </div>
                          </form>
                        {% else %}
                        <button id="openModalBtn" class='btn btn-success btn-sm'>Add to Cart</button>
                        {% endif %}  
                    </div>
                </div>
            </div>
    </div>
</div>

<div id="myModal" class="modal">
    <div class="modal-content w-50">
      <span class="close right">&times;</span>
      <div class='w-50 m-auto'>
        <form method="post" action="{% url 'login_view' %}">
            {% csrf_token %}
            {{ login.as_p }}
            <input type="hidden" name="next" value="{% url 'add_to_cart' product.id %}">
            <button type="submit" class='btn btn-sm btn-primary'>Entrar</button>
          </form>
      </div>
      
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
 $(document).ready(function(){
  // Evento de clique no botão para abrir o modal
  $("#openModalBtn").click(function(){
    $("#myModal").css("display", "block");
  });

  // Fecha o modal ao clicar no botão de fechar
  $(".close").click(function(){
    $("#myModal").css("display", "none");
  });

  // Fecha o modal ao clicar fora do conteúdo do modal
  $(window).click(function(event){
    if(event.target === $("#myModal")[0]) {
      $("#myModal").css("display", "none");
    }
  });
});


</script>


{% endblock container %}

templates/store/order_list.html
{% extends 'base.html' %} 
{% load static %}

{% block container %}



    <div class="cart-container w-75 m-auto p-2  bg-light" style="margin-top: 7rem!important;">
        <h2><i class="fa-solid fa-basket-shopping"></i> My purchases</h2>
        {% if orders %}
                <ul class=" w-100">
                    {% for order in orders %}
                        <li class='row m-2 border rounded-2 shadow shadow-sm  '>
                            {% for item in order.items.all  %}
                            <div class="col p-2 text-center " style="background-color: rgba(255, 255, 255, 0.8)">
                                <div><b>Product = </b> <span class="text-uppercase">{{item.product.category.name}} {{item.product.name}}</span></div>
                                <div><b>Price per unit = </b><span class="text-uppercase"></span>${{item.product.price}}</span></div>
                                <div></div>
                                <img  src="{{item.product.image.url}}" class="card-img-top p-4 w-50 h-auto col" alt="pizza">
                            </div>
                            {% endfor %}
                            <div class='col-6'>
                                <div class="card-body pt-2">
                                    <h3>General information</h3>
                                    <hr>
                                    <p class="m-0"><b>Purchase date =</b> {{ order.order_date }}</p>
                                    <p class="m-0"><b>Billing address =</b> {{ order.billing_address }}</p>
                                    <p class="m-0"><b>Total value= </b> ${{ order.total_price|floatformat:2 }}</p>
                                </div>
                            </div> 
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
            <p class="text-center">Your cart is empty. <a href="{% url 'home' %}">Browse our products</a>.</p>
            {% endif %}
        
    
    </div>
{% endblock container %}

templates/store/order_purchase.html
{% extends 'base.html' %} {% load static %}

{% block container %}
<div class="cart-container w-50 m-auto p-2  bg-light" style="margin-top: 7rem!important;">
    <h2>Purchase</h2>
    {% if orders %}
        <ul>
            {% for order in orders %}
                <li class='row row-cols-2 m-2 shadow shadow-sm p-2'>
                    <div class='col-2 rounded-start-5'>
                        <img src="{{order.product.image.url}}" alt="" class='w-50'>
                    </div>
                    <div class='col pt-3'>{{ order.product }} | Quantity: <b>{{ order.quantity }}</b> | Size: {{ order.size }}</div>
                </li>
            {% endfor %}
        </ul>
        <div class='m-4 row row-cols-2 border rounded-5 w-50'>
            <div class="col-2 text-center p-3 bg-secondary">
                <i class="fa-solid fa-coins"></i>
            </div>
            <div class="col-6">
                <p class='p-0 m-0'>Total = {{total_items}} itens</p>
                <p class='p-0 m-0'>Preço total = ${{total_price}}</p>
            </div>
        </div>
        <form action="" method="post" class='shadow d-block w-75 m-auto p-3 d-flex'>
            {% csrf_token %}
            <div class='col'>
                <div class='m-2'>
                    <p>{{form.shipping_address.label_tag}}: </p>
                        <p>{{form.shipping_address}}</p>
                </div>
                <div class='m-2'>
                    <div>
                        <p>{{form.billing_address.label_tag}}:</p>
                        <p>{{form.billing_address}}</p>
                    </div>
                </div>
                
                <button type="submit" class="btn btn-sm btn-success d-block w-50 m-auto mt-2 mb-2">Complete purchase</button>
            </div>
            <div class='col m-1 p-2'>
                <h1>Attention<i class="fa-solid fa-exclamation"></i></h1>
                "If your address is not appearing on the list, go to 'My Profile' and add the address, then return to the cart to proceed with the purchase."
            </div>
        </form>
    {% else %}
        <p>You have no orders yet.</p>
    {% endif %}

    

</div>

{% endblock container %}

templates/store/product_list.html
{% extends 'base.html' %} 
{% load static %}

{% block container %}

<h1>Product List</h1>
    {% if products %}
        <ul>
            {% for product in products %}
                <li>{{ product.name }} - {{ product.price }} <a href="#">Add to Cart</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No products available.</p>
    {% endif %}


{% endblock container %}